// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLR4MuUOhSV4rlSgKJrav0nqnnJmmtwQg',
    appId: '1:1077457841892:web:96178cb9c31ab59cb246f1',
    messagingSenderId: '1077457841892',
    projectId: 'lunalifts-62f94',
    authDomain: 'lunalifts-62f94.firebaseapp.com',
    storageBucket: 'lunalifts-62f94.appspot.com',
    measurementId: 'G-FN9V258J63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDayz8UC2jNZP9NwHN79sSkmEVCKwUuMU8',
    appId: '1:1077457841892:android:5363551b1a939060b246f1',
    messagingSenderId: '1077457841892',
    projectId: 'lunalifts-62f94',
    storageBucket: 'lunalifts-62f94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV6ZLw9ot0gmJZ4UO1aZuGZTo4JLhmJEo',
    appId: '1:1077457841892:ios:7d0a9558e966fdb1b246f1',
    messagingSenderId: '1077457841892',
    projectId: 'lunalifts-62f94',
    storageBucket: 'lunalifts-62f94.appspot.com',
    iosBundleId: 'com.example.lunalifts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV6ZLw9ot0gmJZ4UO1aZuGZTo4JLhmJEo',
    appId: '1:1077457841892:ios:7d0a9558e966fdb1b246f1',
    messagingSenderId: '1077457841892',
    projectId: 'lunalifts-62f94',
    storageBucket: 'lunalifts-62f94.appspot.com',
    iosBundleId: 'com.example.lunalifts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLR4MuUOhSV4rlSgKJrav0nqnnJmmtwQg',
    appId: '1:1077457841892:web:9ce48cca5b8ed761b246f1',
    messagingSenderId: '1077457841892',
    projectId: 'lunalifts-62f94',
    authDomain: 'lunalifts-62f94.firebaseapp.com',
    storageBucket: 'lunalifts-62f94.appspot.com',
    measurementId: 'G-FSQJQD5PRL',
  );

}